# Generated by Django 5.0.2 on 2024-03-08 14:42

import datetime
import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    'count',
                    models.IntegerField(
                        blank=True,
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=15, null=True
                    ),
                ),
                ('payment_status', models.BooleanField(default=False)),
                (
                    'lifetime',
                    models.DateTimeField(
                        default=datetime.datetime(2024, 3, 8, 14, 44, 44, 169050)
                    ),
                ),
            ],
        ),
    ]
