# Generated by Django 5.0.2 on 2024-03-17 20:46

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_created_at_alter_order_lifetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lifetime',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 17, 20, 48, 31, 756008)
            ),
        ),
    ]
