# Generated by Django 5.0.2 on 2024-03-01 17:54

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=2)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2024, 3, 8, 17, 54, 47, 30833))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='products.product')),
            ],
        ),
    ]
