# Generated by Django 5.0.2 on 2024-03-01 17:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 17, 57, 7, 320529)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
