# Generated by Django 5.0.2 on 2024-03-02 00:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_sale_end_date_alter_sale_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 0, 15, 22, 701309)),
        ),
    ]
