# Generated by Django 5.0.2 on 2024-03-05 18:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_sale_product_product_sale_alter_sale_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 18, 3, 28, 632897)),
        ),
    ]
