# Generated by Django 5.0.2 on 2024-03-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopstaffgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codename__startswith': 'product'}, to='auth.permission'),
        ),
    ]
