# Generated by Django 5.0.2 on 2024-03-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0002_alter_shopstaffgroup_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopstaffgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codename__endswith': ('product', 'sale')}, to='auth.permission'),
        ),
    ]
