# Generated by Django 5.0.2 on 2024-03-08 14:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "end_date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 3, 15, 14, 42, 44, 165969)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=99.99, max_digits=15),
                ),
                ("public", models.BooleanField(default=False)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="products",
                        to="category.category",
                    ),
                ),
            ],
        ),
    ]
