# Generated by Django 5.0.2 on 2024-03-08 14:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 15, 14, 42, 54, 487589)
            ),
        ),
    ]
