# Generated by Django 5.0.2 on 2024-03-01 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lifetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 20, 37, 0, 893012)),
        ),
    ]
