# Generated by Django 5.0.2 on 2024-03-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        default='Category Name', max_length=120, unique=True
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
            ],
        ),
    ]
