# Generated by Django 5.0.2 on 2024-03-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='id',
            field=models.BigIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
