# Generated by Django 5.0.2 on 2024-03-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Article title", max_length=120)),
                (
                    "article_content",
                    models.TextField(
                        blank=True, default="Article body", max_length=512, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "mark",
                    models.IntegerField(
                        choices=[
                            (1, "Awfull"),
                            (2, "Bad"),
                            (3, "Not bad"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        default=5,
                    ),
                ),
            ],
        ),
    ]
