# Generated by Django 5.0.2 on 2024-03-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("searching", "Searching"),
                    ("in-process", "In-process"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                max_length=10,
            ),
        ),
    ]
